### ISSUE TITLE
Invalid layout ground truth in a few examples

### ISSUE THREAD

**Issue by sunset1995** [bertjiazheng/Structured3D#1]
Thank you for sharing the useful dataset!
I have trained [HorizonNet](https://github.com/sunset1995/HorizonNet) on Structured3D for general layout.
I found some confusing example during testing:
![螢幕快照 2019-08-21 上午10 30 40](https://user-images.githubusercontent.com/2712505/63398054-f4579200-c3fe-11e9-93cd-f6b55028c07a.png)
This is a snapshot from my [results report](https://github.com/sunset1995/HorizonNet/blob/master/README_ST3D.md#invalid-ground-truth).

The top-down view of the ground truth (green solid lines) is **self-intersecting**?
I put the estimated result (red dot lines) for your reference.

**Comment by bertjiazheng** [comment]
Hi @sunset1995 

Nice work! 

There are about 89 self-intersecting cases over 21,835 rooms. We have checked the original house designs. The self-intersecting layout occurs due to some strange designs. We would try to fix them if possible. For now, you can just skip these cases. 

Best,
Jia
