### ISSUE TITLE
Scene point cloud distorted

### ISSUE THREAD

**Issue by micaeltchapmi** [bertjiazheng/Structured3D#11]
Hi,

Thanks again for this great dataset. I want to generate a point cloud of a scene from rgbd perspective images and camera poses but the point cloud is distorted as shown below. The point cloud below is obtained from scene: 00000 room_id: 485142 and position_id: 0. I used the parse_camera_info function from utils to obtain the camera intrinsics and extrinsics and then generated the point cloud using [rgbd_to_world](https://github.com/thusiyuan/cooperative_scene_parsing/blob/0689c8057757a9efec387c272ddae9074861b07a/utils/net_utils.py#L154) function from the link above as you mentioned that you adapted some of your code from there. Any idea as to what might be causing the distortion? Are there any changes to the rgbd_to_world function I need to do in order to get a more accurate point cloud?

<img width="519" alt="Screen Shot 2020-04-07 at 12 59 10 PM" src="https://user-images.githubusercontent.com/35488694/78714051-06277000-78d0-11ea-9d6f-db2fe61298b2.png">

**Comment by bertjiazheng** [comment]
Hi, 

I think your point cloud generation is correct. These flying pixels are due to the depth rendering. When a pixel is directly at the boundary of an object, the distance is averaged by a mix of the foreground and the background distance. 

Best,
Jia

**Comment by MirceaHotoleanuCluj** [comment]
Hi,

I noticed the same effect by using the depth info in panoramic views. My work-around was to "erode" (scipy.ndimage.morphology.binary_erosion)  the masks of the objects. That eliminates one pixel from the objects' frontier and thus eliminates the "plying pixels".

**Comment by bertjiazheng** [comment]
Hi @micaeltchapmi @MirceaHotoleanuCluj 

We have fixed the flying pixels issue for the _perspective image_ and provide a more accurate depth map. You can redownload the data if you want to use it.

Best,
jia

**Comment by javrtg** [comment]
Hi @bertjiazheng, would it be possible to also solve this issue for panoramic depth? I feel that this might require a lot of work, so thank you either way for open-sourcing such a great dataset!

**Comment by bertjiazheng** [comment]
Hi @javrtg,

Thank you for your suggestion! 

Unfortunately, since Structured3D was released five years ago, and some team members have departed, we cannot add new data to this dataset.

However, we are excited to announce that we will soon release a new panoramic video dataset, which was used to train [SpatialLM](https://github.com/manycore-research/SpatialLM) and [SpatialGen](https://github.com/manycore-research/SpatialGen). We hope this new dataset will be an enhanced version of the Structured3D dataset. Please stay tuned for updates!

Best regards,
Jia

**Comment by javrtg** [comment]
That's completely understandable, thanks for the quick response!

Also thanks for letting me know about SpatialLM and SpatialGen's datasets, they look very promising.
I have looked at [SpatialGen's test set](https://huggingface.co/datasets/manycore-research/SpatialGen-Testset) and the quality of the perspective images looks excellent. I am curious, do you also plan to release the panoramic images? They would be very useful for my use case.

**Comment by bertjiazheng** [comment]
@javrtg Yes, we will release the panoramic renderings.

**Comment by javrtg** [comment]
That's great! Thanks again @bertjiazheng and thanks also for your and your team's contributions!
