### ISSUE TITLE
Are there Instance annotations for the Panorama?

### ISSUE THREAD

**Issue by micaeltchapmi** [bertjiazheng/Structured3D#12]
Hi,

I would like to know if you can provide instance annotations for the Panoramas? Otherwise, is there a way to convert instance annotations from the perspectives to the Panoramas?

Thanks,

Micael

**Comment by bertjiazheng** [comment]
Hi,

Currently, we do not provide instance annotations for the panoramas. We will work on it soon. Since the pose and positions of the camera are different for two sets, it would be hard to convert. 

Best,
Jia

**Comment by bertjiazheng** [comment]
Hi @micaeltchapmi 

FYI, we recently released the instance annotation for the panoramas.

Best,
Jia

**Comment by micaeltchapmi** [comment]
Hi @bertjiazheng ,

Does the instance annotation on the panoramas include instance ids for each wall, floor and ceiling?

Thanks,

Micael

**Comment by bertjiazheng** [comment]
The instance map only contains furniture instances. But you can get the instance map of the wall, floor, and ceiling by projecting the 3D planes saved in `annotation_3d.json`.

Best,
Jia

**Comment by micaeltchapmi** [comment]
@bertjiazheng I'm not sure how to project the 3d coordinates of the walls, floors and ceilings on the panorama images. I looked at the `project_3d_points_to_2d` you have and it requires intrinsic and extrinsic parameters for the camera. In `camera_xyz` for the panoramas, we have only the camera position. Can you give me some insights as to how to do this projection on the panoramas?

**Comment by bertjiazheng** [comment]
Please check the [xyz_2_coorxy](https://github.com/bertjiazheng/Structured3D/blob/d9a7f618d8610f82f7847169ac2aac910e708b7d/misc/panorama.py#L8_L13) function.

**Comment by micaeltchapmi** [comment]
@bertjiazheng I projected the 3D planes to the panoramas using scene_00000 but the projection seems a little off. For example the floor with plane id 2 shown below seems to be projected in the middle of the image and the polygon formed by projecting the ceiling (plane id 3) seems to not cover the edges of the ceiling as shown. Can you help me understand why this might be happening and how I can get good projections?

<img width="392" alt="Screen Shot 2020-08-13 at 11 04 18 PM" src="https://user-images.githubusercontent.com/35488694/90219134-3e791680-ddba-11ea-971f-c8a69b52162d.png">
<img width="388" alt="Screen Shot 2020-08-13 at 11 03 50 PM" src="https://user-images.githubusercontent.com/35488694/90219145-433dca80-ddba-11ea-9998-13820ea2f16a.png">

Here is the code I used and I run it with `python panorama.py --path path/to/data --scene 00000` 
[panorama.py.zip](https://github.com/bertjiazheng/Structured3D/files/5072899/panorama.py.zip)

**Comment by bertjiazheng** [comment]
You probably forget to subtract the camera position.

**Comment by micaeltchapmi** [comment]
You're right. Looks much better now. Thank you!
