### ISSUE TITLE
camera height setting in rendering panorama images

### ISSUE THREAD

**Issue by bing-jian** [bertjiazheng/Structured3D#18]
Hi,

The paper says "At the time of rendering, a panoramic or pin-hole camera is placed at random
locations not occupied by objects in the room".  Is the camera height also random or a fixed height?

Thanks,
Bing

**Comment by bertjiazheng** [comment]
Hi Bing,

Yes, the camera height is also random. You can found the 3D location of the camera in the _camera_xyz.txt_ or _camera_pose.txt_. 

Best,
Jia
