### ISSUE TITLE
Partially missing of Structured3D_perspective_full dataset

### ISSUE THREAD

**Issue by nobodypengium** [bertjiazheng/Structured3D#19]
Hi,

Thanks for your wonderful dataset.

I download the dataset you provide from the link you shared with nobodypeng@bupt.edu.cn. However, I found that ```Structured3D_perspective_full_08.zip``` and ```Structured3D_perspective_full_09.zip``` are the same. They are all from ```scene_01800``` to ```scene_01999```. And md5 sum of both of them is ```4acc9d203b750e6e7e1c24d0d670ebee```

Scenes between ```scene_01600``` and ```scene_01799``` seems missing. It seems that ```Structured3D_perspective_full_08.zip``` should start from ```scene_01600``` but start from ```scene_01800```
Could you please share the missing part? Thanks a lot.

**Comment by bertjiazheng** [comment]
Hi, 

I am sorry that this part of the data is missing due to our negligence. For now, you can ignore this set.

Best,
Jia

**Comment by nobodypengium** [comment]
> Hi,
> 
> I am sorry that this part of the data is missing due to our negligence. For now, you can ignore this set.
> 
> Best,
> Jia
That's fine. Thanks for your reply.

**Comment by YunfanZhang42** [comment]
Following up here. I am assuming this issue is still in place, and we can ignore Structured3D_perspective_full_09 for now?

**Comment by bertjiazheng** [comment]
Yes, I could not find that chunk anymore. Please just skip it.

Best,
Jia
