### ISSUE TITLE
What kinds of planes are available?

### ISSUE THREAD

**Issue by GuardianWang** [bertjiazheng/Structured3D#2]
Thank you for your outstanding work!

I have a question about available plane labels. I notice that in Figure 1 (b) Planes of your paper, several walls are labeled. So I wonder have you just labeled walls, or your dataset actually provides planar labels of all kinds of objects?

![360截图17571122107150157](https://user-images.githubusercontent.com/31812793/64532496-3318a200-d344-11e9-8489-7d32020e0840.jpg)

Thank you.

**Comment by bertjiazheng** [comment]
Hi, 

As we claim in the [preprint paper](https://arxiv.org/abs/1908.00222):
> Note that in this work we focus on extracting ground truth annotations on the room structure only. We plan to extend our dataset to include 3D structure annotations of individual furniture models in the future.

Best,
Jia

**Comment by GuardianWang** [comment]
Thank you.
