### ISSUE TITLE
Some files corresponding to the room semantic annotation in annotation_3d.json file are missing

### ISSUE THREAD

**Issue by AK250** [bertjiazheng/Structured3D#20]
Hi,
Thanks for your excellent work!
I noticed that in addition to the room、window、door categories, there is also undefined in semantic field in annotation_3d.json file, what does undefined mean? Does that mean a room but the function is not clear or just has no semantic label?
And I find that some ID in in semantic field in annotation_3d.json file has no relative image, eg, scene_00147: 2113 which is labeled as balcony, scene_00092: 234 which is labeled as bathroom.
![image](https://user-images.githubusercontent.com/78076775/137262317-fad94352-9f5e-48a8-95a5-cc3a3fdcb222.png)

**Comment by bertjiazheng** [comment]
Hi,

Thanks for your interest in our dataset!

1. The "undefined" means the undefined room. 
2. For some small spaces (such as the balcony and the bathroom as you mentioned), it is hard to render a meaningful image. We remove these renderings from our dataset, but the 3D annotation also contains these rooms. 

Best,
Jia
