### ISSUE TITLE
Dataset Files are corrupted

### ISSUE THREAD

**Issue by hermannsblum** [bertjiazheng/Structured3D#22]
I tried to download the dataset, but found both `Structured3D_perspective_full_00.zip` and `Structured3D_perspective_full_01.zip` to be corrupted, so I stopped the downloading.

When trying to unzip the archives, I get the following error: 
```
Archive:  Structured3D_perspective_full_00.zip
warning [Structured3D_perspective_full_00.zip]:  8326737875 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Structured3D_perspective_full_00.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
I tried multiple zip tools, but it is the same for all of them. Are the files corrupted, or is this not a zip archive, or compressed with a special algorithm?

**Comment by bertjiazheng** [comment]
Could you please try the method mentioned in [here](https://github.com/CYang0515/NonCuboidRoom/issues/6#issuecomment-977859317)?

**Comment by hermannsblum** [comment]
Thanks for the quick answer! Based on that comment, I tried if these are actually 7zip files, and that worked.
So for anybody on ubuntu, these are the steps: 
```
sudo apt install p7zip-full
7z x Structured3D_perspective_full_00.zip
```
