### ISSUE TITLE
Missing parts in fused point clouds

### ISSUE THREAD

**Issue by ywyue** [bertjiazheng/Structured3D#26]
Hi,

Thanks for the great work! I am trying to generate point cloud from the dataset. I follow this [script](https://gist.github.com/bertjiazheng/c43066678c9070448d7076291d0d30d9) and generate the point cloud for scene_00000 based on the Structured3D_perspective_full_00 dataset. However, there are some missing parts obviously. Do you think this is normal or is there a way to generate a more complete point cloud? Thanks in advance!

![image](https://user-images.githubusercontent.com/40747438/169414713-59b6d578-fb7a-4d38-9b2d-42ca3ea22d84.png)

Best,
Yue

**Comment by bertjiazheng** [comment]
Hi,

Thanks for your interest in our dataset. 

We only sample a few views (e.g., no more than 5 views per room) in the dataset. Thus, it is obvious there are many uncovered regions.

Best,
Jia

**Comment by ywyue** [comment]
Alright, thanks!

**Comment by bertjiazheng** [comment]
Hi,

The point cloud will be much better using panorama images. You could make the fusion code for the perspective image adapt to the panoramic image with some modifications.

BTY, I will try to update the fusion code in the following days.

Best,
Jia

**Comment by ywyue** [comment]
Hi thanks for your reply! Actually, I just got the preprocessing script from the author of (https://arxiv.org/abs/2103.11161). BTW, I will also try to modity the fusion code to make it work for the panoramic image.

**Comment by bertjiazheng** [comment]
That's great!

**Comment by ywyue** [comment]
Hi , I managed to generate point cloud from panoramic image using the code from [here](https://github.com/bertjiazheng/Structured3D/issues/9#issuecomment-610730836). It works well for most of the scenes. However, for some scenes (e.g. scene_01401, see screenshoot below), there are some discrepancy between the point cloud and the floorplan/wireframe. I suspect that there are some mistakes in the annotation (but I am not sure as structured3d is synthetic data). On the other hand, I think the code is correct so the generated point cloud should also be correct. So I am quite confused and curious about the reason. Could you give some hints?
![Picture1](https://user-images.githubusercontent.com/40747438/171966221-e8d4dccb-bccd-47c8-84d8-b53616736326.png)

**Comment by bertjiazheng** [comment]
Hi @ywyue,

As you can see, the occlusion may exist, for example the cabinet as you pointed out by the red circle.

Best,
Jia

**Comment by ywyue** [comment]
Hi Jia, Thanks for your reply. I see the reason. I also check the corresponding rgb image for the region in the red circle. Yes, the missing part is occluded by the cabinet. 
![Picture3](https://user-images.githubusercontent.com/40747438/172954800-dd42f034-fd3c-48ad-b4dc-9c4e8e25d09c.png)

**Comment by bertjiazheng** [comment]
Hi @ywyue,

The current dataset only focuses on the room structure. However, we also provide the 3D bounding box information of the furniture. You may have a try. But, I do not think it is an easy way to use this information to modify the floorplan.

Best,
Jia

**Comment by ywyue** [comment]
Hi Jia, alright, thanks for your comments!
