### ISSUE TITLE
Dataset download fails

### ISSUE THREAD

**Issue by vevenom** [bertjiazheng/Structured3D#3]
Hi,

I noticed that when downloading the dataset from OneDrive, the operation fails(always), at least for my Ubuntu 16 system. I guess the problem is with unstable OneDrive server.

I was able to solve this issue by using a download manager.

**Comment by ltindall** [comment]
@vevenom  How did you resolve this issue? My downloads are also always failing.

**Comment by vevenom** [comment]
So if you want to download specific files individually, you can just use resume/retry download button in your browser every time the download fails, until you complete the download. XD

Otherwise, you need some kind of a download manager that does this for you. To be honest, I am not sure which software I used to download the dataset but if it has automatic resume feature, it will do the trick.

**Comment by WXR1998** [comment]
You may try the Internet Download Manager(IDM). It helps.

**Comment by zhezh** [comment]
from my experiences, you can only download files from onedrive by click download on the website, wget the url will fail. An alternative is to use Onelist to create permanent link for each file(need the account owner to run the service), then you can wget the link.

**Comment by YunfanZhang42** [comment]
I second the comment above. The current OneDrive sharing site does not support cURL or wget and could only be downloaded manually in browser. Also the site seem to limit the number of concurrent downloads to only 2 at the same time. This means it takes 1+ days to download the dataset and you have to wait in front of your computer. Hopefully some better workflows will be in place!

**Comment by bertjiazheng** [comment]
Please also refer to #25 if you have the same question.

**Comment by C-H-Chien** [comment]
Hi, I am using Ubuntu and I tried XDM for downloading the dataset but it still failed every time. Direct download did not work as well. I wonder whether there is an alternative solution to have a successful download? Thanks!

**Comment by Harvey-Mei** [comment]
> Hi, I am using Ubuntu and I tried XDM for downloading the dataset but it still failed every time. Direct download did not work as well. I wonder whether there is an alternative solution to have a successful download? Thanks!

Hello Chien,
You need to enter the ubuntu desktop environment and start the download task with a browser to get the download link. Then copy the download link of the task and use it to create a download task in XDM.
I downloaded it successfully through the above method, and the download speed is also very fast.

**Comment by Eotia-was-taken** [comment]
Hey guys,
I am really struggling with downloading the dataset. All download links are the same and lead to a broken download. I tried using XDM but it fails to connect.

**Comment by bertjiazheng** [comment]
Hi all,

We have already transferred the data to Azure drive.  We hope that the downloading process will be stable and fast for you.

Please refill the [agreement form](https://forms.gle/LXg4bcjC2aEjrL9o8) to access the download link. 

Best,
Jia
