### ISSUE TITLE
Some questions about dataset

### ISSUE THREAD

**Issue by kimkj38** [bertjiazheng/Structured3D#31]
Thanks for your great work first and I have some questions about the dataset you released.

1. There are 3 perspective images and panorama of 05/scene01005/159. I want to make point cloud of the scene but I guess that I can't get enough point clouds of the scene because the perspective images are very local. Is there any other information?

![스크린샷 2023-03-16 오후 3 36 54](https://user-images.githubusercontent.com/76815825/225536056-5edc56d3-d514-4443-826f-b160501e6faa.png)
![스크린샷 2023-03-16 오후 3 37 00](https://user-images.githubusercontent.com/76815825/225536066-94d6e115-573e-4e36-8dc4-ea7631c278cc.png)
![스크린샷 2023-03-16 오후 3 37 06](https://user-images.githubusercontent.com/76815825/225536069-abdac3f0-1306-4325-aa9e-7e4fa1521f8e.png)
![스크린샷 2023-03-16 오후 3 42 46](https://user-images.githubusercontent.com/76815825/225536071-3d480e52-e472-4166-92f6-8b1e1f60e709.png)

2. Unlike perspective image, there's only xyz of camera pose in panorama. How can I get rotation of panorama image?

3. I thought I can get panoptic segmentation GT with your instance.png and semantic.png.( e.g. chair1 & chair2) But I couldn't understand how I can use instance.png because it's just binary information that divide whether it is object or not. Could you let me know how I can utilize instance information you provided?

**Comment by bertjiazheng** [comment]
Hi,

Thanks for your interest in our dataset. Here are some answers: 

1. I am afraid there is no other better option. 
2. For panorama images, the direction of the camera is always along the negative y-axis. 
3. You should read the instance with the correct format. The instance map is coded with unsigned 16-bit integers.

I hope this helps. Feel free to ask if you have any other questions. 

Best,
Jia

**Comment by kimkj38** [comment]
Thanks for your help and I have additional questions.

I hope to make 2D bounding boxes of the panorama images from 3D bounding boxes by projection. 

But there're 4 panorama images in scene_00000 and all the box information is included in bbox_3d.json so that I can't match the object and the panorama.

Also, I need the class of bounding box but I can't find it.

Can I solve these problems with your data?

**Comment by bertjiazheng** [comment]
You can obtain the 3D bounding boxes of the visible objects by associating the "ID" in _bbox_3d.json_ and the values in _instance.png_.

It is unstraightforward to obtain the semantic information of the bounding box. But you can still obtain it by associating the _instance.png_ and _semantic.png_.

Best,
Jia

**Comment by kimkj38** [comment]
I understood. Thank you!
