### ISSUE TITLE
Global coordinates

### ISSUE THREAD

**Issue by kimkj38** [bertjiazheng/Structured3D#32]
Hi,

I'm trying to generate 2D bounding box in panorama image and made the below code.

But the result x-axis pixel looks weird(white pixels are instance and the red point is projected centroid) and I found that the global coordinate system is arbitrary on Data Organization.md.

I thought y-axis is (0,1,0) and the camera pose is negative y-axis in panorama.

But global y-axis is all different for each scene? If so, how can I know that?  

![image](https://user-images.githubusercontent.com/76815825/226299107-c3a92127-dc66-411a-8875-a0512773c29a.png)
![image](https://user-images.githubusercontent.com/76815825/226299271-d209b032-c431-43fd-9c05-bbd2cad9744b.png)

**Comment by bertjiazheng** [comment]
Sorry for the confusion. The global system is not arbitrary. The camera (i.e., the center position of the panorama image) is looking at the negative y-axis.

**Comment by kimkj38** [comment]
x,y,z axis is (1,0,0), (0,1,0), (0,0,1) and negative y-axis is (0, -1, 0)?
Or global axis is different?

**Comment by kimkj38** [comment]
I think the global coordinate system is different for each scene because 2D centroid is aligned well when I change z-axis rotation properly. Is it right?

**Comment by bertjiazheng** [comment]
The direction of the axis without a coordinate system is nonsense. 

To transform the world coordinate into the camera coordinate, you should use the following rotation matrix:
```python
R = [[1, 0, 0], [0, 0, -1], [0, -1, 0]]
```

**Comment by kimkj38** [comment]
When I saw the point cloud of the 3D scene, the z-axis was downward unlike you mentioned at the data organization. So, `R = [[1, 0, 0], [0, 0, 1], [0, -1, 0]]` worked well for 2D projection. Could you check it again?

**Comment by bertjiazheng** [comment]
How do you obtain the point cloud?

**Comment by kimkj38** [comment]
I made it with panorama rgb and depth

**Comment by kimkj38** [comment]
Sorry, I see the point cloud again and the z-axis is upward.(axes are BGR order). You're right.

But I still don't understand why `R = [[1, 0, 0], [0, 0, 1], [0, -1, 0]]` works well.

Global coordinate is black,  red 1 is your matrix and red 2 is my matrix on the second figure.

Which one is right?


![image](https://user-images.githubusercontent.com/76815825/228426619-54ee36cc-cf89-435f-a7b0-3182ee68641b.png)

![image](https://user-images.githubusercontent.com/76815825/228427981-82c43927-2841-44b4-ac05-64c7d845b83d.png)

**Comment by kimkj38** [comment]
This is the result!

![image](https://user-images.githubusercontent.com/76815825/228429109-8a3dd8de-10f5-41f0-9bdc-7a220f886ee7.png)
