### ISSUE TITLE
Can not download Structurd3d_perspective_full_00.zip

### ISSUE THREAD

**Issue by jemo-mh** [bertjiazheng/Structured3D#35]
Filling agreement form, I accessed azure cloud readme.txt

Downloading dataset, I noticed one link 
`Structured3D_perspective_full_00.zip` can't  download now.

Pasted web message below
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:919e4d03-401e-0060-2cad-63b674000000 
Time:2023-03-31T08:47:06.5975716Z</Message>
</Error>`

-- 
Using wget to download that link, error log is below
`--2023-03-31 17:43:08--  https://zju-kjl-jointlab-azure.kujiale.com/zju-kjl-jointlab/Structured3D/Structured3D_perspective_full_00.zip
Resolving zju-kjl-jointlab-azure.kujiale.com (zju-kjl-jointlab-azure.kujiale.com)... 61.110.192.11, 61.110.192.59
Connecting to zju-kjl-jointlab-azure.kujiale.com (zju-kjl-jointlab-azure.kujiale.com)|61.110.192.11|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-31 17:43:09 ERROR 404: Not Found.`

Thanks for your help!

**Comment by bertjiazheng** [comment]
Sorry for missing this file earlier. However, I have fixed the issue and the file is now available for you to access. Please let me know if you have any further concerns or questions.

**Comment by jemo-mh** [comment]
> Sorry for missing this file earlier. However, I have fixed the issue and the file is now available for you to access. Please let me know if you have any further concerns or questions.

It works now. 
Thanks for your reply :)
