### ISSUE TITLE
Camera information for  panorama imge

### ISSUE THREAD

**Issue by jemo-mh** [bertjiazheng/Structured3D#36]
Hello,

Is there any way to get intrinsic and extrinsic matrix to calibrate panorama images???

Thanks in advance!

**Comment by jemo-mh** [comment]
> You can find the camera location of the panorama in `camera_xyz.txt`. The direction of the camera is always along the negative y-axis. The z-axis is upward.

Thanks for you reply!
Is there any way to get K matrix (fx, fy, cx, and cy ) of panorama images?

**Comment by bertjiazheng** [comment]
I am not aware of the intrinsic matrix for the panorama camera.
