### ISSUE TITLE
Missing annotation in Scene_00013

### ISSUE THREAD

**Issue by pengzhi1998** [bertjiazheng/Structured3D#37]
Dear authors, thank you so much for providing this great dataset! 

However, after downloading and unzipping [Structured3D_panorama_00.zip](https://zju-kjl-jointlab-azure.kujiale.com/zju-kjl-jointlab/Structured3D/Structured3D_panorama_00.zip), we found there is no _**annotation_3d.json**_ under scene_00013 directory. 

We apologize for any inconvenience and appreciate your help!

**Comment by bertjiazheng** [comment]
Hi,

We have uploaded all 3D structure annotations. You can find the download link in the README file. 

Best,
Jia
