### ISSUE TITLE
Clarify mapping for semantic labels

### ISSUE THREAD

**Issue by aluo-x** [bertjiazheng/Structured3D#4]
It doesn't seem to be written anywhere, but the Structured3D seems to be using the ScanNet class to color mappings as provided here:
[util.py:Line 82](https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/util.py#L82)

Would be great if this could be documented, and if some code that could convert this to a 1...40 representation.

**Comment by bertjiazheng** [comment]
Hi Andrew, 

Yes, we use the color palette from the ScanNet dataset. Another easier way is to use the PIL image library, you can directly get the semantic ids instead of RGB colors. 

Best,
Jia

**Comment by aluo-x** [comment]
Thanks for the update. I was not aware that PIL had this functionality. Closing the issue now.
