### ISSUE TITLE
How can I visualize a manhattan plane?

### ISSUE THREAD

**Issue by godhj93** [bertjiazheng/Structured3D#40]
Hi! I am interested in utilizing manhattan annotations in your dataset.

Can you guide me on how to visualize Manhattan planes as depicted in the given figure(b)?

![Screenshot from 2023-07-05 05-12-12](https://github.com/bertjiazheng/Structured3D/assets/70679753/5704f100-11da-46ef-b8e3-51fea26142c8)

**Comment by bertjiazheng** [comment]
Try the following args:
```
python visualize_3d.py --type plane --color manhattan
```

**Comment by godhj93** [comment]
Thanks!
