### ISSUE TITLE
How can I visualize wireframes in a perspective image?

### ISSUE THREAD

**Issue by godhj93** [bertjiazheng/Structured3D#41]
Hi there,

I'm currently trying to visualize wireframes in a perspective view and I have some difficulties understanding a few things.

From what I understand, there are two types of annotation files - 'annotation_3d.json' for each scene and 'layout.json' for each perspective view of each scene. However, I'm struggling to comprehend the relationship between the 'lineJunctionMatrix' in 'annotation_3d.json' and the 'junctions' in 'layout.json' for wireframe visualization.

Is there available code that can illustrate how these concepts are connected?

Any advice or direction you could give me on this would be greatly appreciated.

I also want to know what junctions's ID is "None" in "layout.json" means

Thank you so much for your time and assistance!

**Comment by bertjiazheng** [comment]
Hi,

You can find more details in [data_organization.md](https://github.com/bertjiazheng/Structured3D/blob/master/data_organization.md) about these annotations. 

Here are some clarifications. 

- The `annotation_3d.json` is the annotation of the house design, while the `layout.json` is the annotation of the corresponding perspective image. 
- In `layout.json`, the junctions with `none` ID correspond to fake junctions (such as junctions created by the intersections between the room wireframe and image boundary).

Best,
Jia
