### ISSUE TITLE
How to render novel views

### ISSUE THREAD

**Issue by qhz991029** [bertjiazheng/Structured3D#45]
Thank you for your brilliant dataset!

I have a NeRF related task, which requires more images than the provided ones in the dataset. I wonder if there's any method to render more views of the scenes/rooms?

Best regards.

**Comment by bertjiazheng** [comment]
Unfortunately, we do not provide any rendering services. However, you may want to check out [MINERVAS](https://coohom.github.io/MINERVAS).
