### ISSUE TITLE
issue extracting the zip files

### ISSUE THREAD

**Issue by satyapalsinh10** [bertjiazheng/Structured3D#46]
hi, I downloaded the dataset zip file for perspective data from the given link and tried to extract the zip but it shows an error and I cannot extract it.

Additionally, when I try to unzip the downloaded dataset the extracted files for the Panorama dataset are missing the bbox_3d.json file.

can you please help?

**Comment by bertjiazheng** [comment]
1. Please refer to https://github.com/bertjiazheng/Structured3D/issues/22#issuecomment-995614671.
2. For all 3D bounding box annotations, download the Structured3D_bbox.zip file.
