### ISSUE TITLE
How can I get fully structured datasets?

### ISSUE THREAD

**Issue by Leon1207** [bertjiazheng/Structured3D#47]
Why the downloaded Structured3D_annotation_3d.zip file only contains instance.png in each scene, but not contains others like semantic.png, normal.png, etc.? Or how can I get them in your provided download links? Thanks.

**Comment by bertjiazheng** [comment]
Please download either panorama or perspective zip files.

**Comment by Leon1207** [comment]
Thanks for your reply.
