### ISSUE TITLE
How do I know which room in the scene each box in bbox_3d.json corresponds to?

### ISSUE THREAD

**Issue by Leon1207** [bertjiazheng/Structured3D#48]
Does the "ID" in bbox_3d.json correspond to the room? Thanks!

**Comment by bertjiazheng** [comment]
The "ID" corresponds to the instance ID in `instance.png`.

**Comment by Leon1207** [comment]
Thanks for reply, so can I know which room in the scene each box corresponds to?

**Comment by bertjiazheng** [comment]
You can obtain this information by calculating the geometric relationships between the object bbox and the room polygon.

**Comment by Leon1207** [comment]
OK, thanks for your advice!
