### ISSUE TITLE
3D_mesh visualization

### ISSUE THREAD

**Issue by satyapalsinh10** [bertjiazheng/Structured3D#49]
Hi, 

I am able to generate the mesh using 

`python visualize_mesh.py --path /path/to/dataset --scene scene_id --room room_id`

However, it is constrained to each room individually. Is there a way to get the mesh of the entire scene?

**Comment by bertjiazheng** [comment]
This can be easily accomplished by using a for loop to generate textured meshes for all rooms in the scene and then visualizing the list of meshes.
