### ISSUE TITLE
How can I generate photo-realistic 2D images?

### ISSUE THREAD

**Issue by github163sl** [bertjiazheng/Structured3D#8]
Hello, I read your paper, but I didn't understand how to generate photo-realistic 2D images. Can you help me？

**Comment by bertjiazheng** [comment]
This work aims to provide rich annotations of 3D structure. For image rendering, we utilize industry-leading rendering engines provided by kujiale.com.

**Comment by github163sl** [comment]
Thank you for your reply. Do you mean that these rendered images are made manually? Isn't it generated by algorithm?

**Comment by bertjiazheng** [comment]
We introduce the rendering algorithm in Section 4.2 of our preprint paper: 
> We have developed a photo-realistic renderer on the top of Embree. Our renderer uses the well-known path tracing method, a Monte Carlo approach to approximating realistic Global Illumination for rendering.
